name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 18 * * *"   # protidin ekbar
  workflow_dispatch:
  push:
    branches: [main, master]
    paths-ignore:
      - "profile/**"
      - "metrics/**"
      - "profile-3d-contrib/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A profile-3d-contrib
          git commit -m "Update 3D contribution graph" || exit 0
          git pull --rebase || true
          git push
